Repository NovaMachina-Mods/ExNihiloSequentia, pull requests merged in 2022-11, with the labels that each got.

#321 Create de_de.json
  src/main/resources/assets/exnihilosequentia/lang/de_de.json
Labels: 1.18, lang

#341 fix crt remove by input doesn't work
  src/main/java/novamachina/exnihilosequentia/common/crafting/SingleItemInputRecipe.java
  src/main/java/novamachina/exnihilosequentia/common/crafting/compost/CompostRecipe.java
  src/main/java/novamachina/exnihilosequentia/common/crafting/crook/CrookRecipe.java
  src/main/java/novamachina/exnihilosequentia/common/crafting/crucible/CrucibleRecipe.java
  src/main/java/novamachina/exnihilosequentia/common/crafting/fluiditem/FluidItemRecipe.java
  src/main/java/novamachina/exnihilosequentia/common/crafting/fluidtransform/FluidTransformRecipe.java
  src/main/java/novamachina/exnihilosequentia/common/crafting/hammer/HammerRecipe.java
  src/main/java/novamachina/exnihilosequentia/common/crafting/sieve/SieveRecipe.java
Labels: improvement, 1.18, bug-fixes

#348 Add Ukraine Language
  src/main/resources/assets/exnihilosequentia/lang/uk_ua.json
Labels: 1.18, lang

#352 change getting translation key from fluids
  src/main/java/novamachina/exnihilosequentia/common/blockentity/barrel/mode/FluidsBarrelMode.java
Labels: improvement, 1.18, bug-fixes

#364 [1.18] Fix Fluids Transformation
  src/main/java/novamachina/exnihilosequentia/common/blockentity/barrel/mode/FluidsBarrelMode.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: improvement, 1.18, bug-fixes

#366 [1.18] Add lang to custom stats
  src/datagen/generated/exnihilosequentia/assets/exnihilosequentia/lang/en_us.json
  src/datagen/main/java/novamachina/exnihilosequentia/client/ExNihiloLangGenerator.java
Labels: improvement, 1.18, bug-fixes

#365 [1.19] Fix fluids transformation
  src/main/java/novamachina/exnihilosequentia/common/blockentity/barrel/mode/FluidsBarrelMode.java
Labels: improvement, bug-fixes, 1.19

#367 [1.19] add lang to custom stats
  src/datagen/generated/exnihilosequentia/assets/exnihilosequentia/lang/en_us.json
  src/datagen/main/java/novamachina/exnihilosequentia/client/ExNihiloLangGenerator.java
Labels: improvement, bug-fixes, 1.19

#368 [1.19] Enable Crafttweaker
  build.gradle
  docsOut/docs.json
  docsOut/docs/mods/ExNihiloSequentia/Composting.json
  docsOut/docs/mods/ExNihiloSequentia/Composting.md
  docsOut/docs/mods/ExNihiloSequentia/Crooking.json
  docsOut/docs/mods/ExNihiloSequentia/Crooking.md
  docsOut/docs/mods/ExNihiloSequentia/Crucible.json
  docsOut/docs/mods/ExNihiloSequentia/Crucible.md
  docsOut/docs/mods/ExNihiloSequentia/Fluid_On_Top.json
  docsOut/docs/mods/ExNihiloSequentia/Fluid_On_Top.md
  docsOut/docs/mods/ExNihiloSequentia/Fluid_To_Item.json
  docsOut/docs/mods/ExNihiloSequentia/Fluid_To_Item.md
  docsOut/docs/mods/ExNihiloSequentia/Fluid_Transform.json
  docsOut/docs/mods/ExNihiloSequentia/Fluid_Transform.md
  docsOut/docs/mods/ExNihiloSequentia/Hammering.json
  docsOut/docs/mods/ExNihiloSequentia/Hammering.md
  docsOut/docs/mods/ExNihiloSequentia/Heat.json
  docsOut/docs/mods/ExNihiloSequentia/Heat.md
  docsOut/docs/mods/ExNihiloSequentia/Sifting.json
  docsOut/docs/mods/ExNihiloSequentia/Sifting.md
  gradle.properties
  src/main/java/novamachina/exnihilosequentia/common/compat/crafttweaker/CompostRecipeManager.java
  src/main/java/novamachina/exnihilosequentia/common/compat/crafttweaker/CrookRecipeManager.java
  src/main/java/novamachina/exnihilosequentia/common/compat/crafttweaker/CrucibleRecipeManager.java
  src/main/java/novamachina/exnihilosequentia/common/compat/crafttweaker/FluidItemRecipeManager.java
  src/main/java/novamachina/exnihilosequentia/common/compat/crafttweaker/FluidOnTopRecipeManager.java
  src/main/java/novamachina/exnihilosequentia/common/compat/crafttweaker/FluidTransformRecipeManager.java
  src/main/java/novamachina/exnihilosequentia/common/compat/crafttweaker/HammerRecipeManager.java
  src/main/java/novamachina/exnihilosequentia/common/compat/crafttweaker/HeatRecipeManager.java
  src/main/java/novamachina/exnihilosequentia/common/compat/crafttweaker/SieveRecipeManager.java
  src/main/java/novamachina/exnihilosequentia/common/compat/crafttweaker/builder/ZenCompostRecipe.java
  src/main/java/novamachina/exnihilosequentia/common/compat/crafttweaker/builder/ZenCrookRecipe.java
  src/main/java/novamachina/exnihilosequentia/common/compat/crafttweaker/builder/ZenCrucibleRecipe.java
  src/main/java/novamachina/exnihilosequentia/common/compat/crafttweaker/builder/ZenFluidItemRecipe.java
  src/main/java/novamachina/exnihilosequentia/common/compat/crafttweaker/builder/ZenFluidOnTopRecipe.java
  src/main/java/novamachina/exnihilosequentia/common/compat/crafttweaker/builder/ZenFluidTransformRecipe.java
  src/main/java/novamachina/exnihilosequentia/common/compat/crafttweaker/builder/ZenHammerRecipe.java
  src/main/java/novamachina/exnihilosequentia/common/compat/crafttweaker/builder/ZenHeatRecipe.java
  src/main/java/novamachina/exnihilosequentia/common/compat/crafttweaker/builder/ZenSeiveRecipe.java
  src/main/java/novamachina/exnihilosequentia/common/crafting/SerializableRecipe.java
  src/main/java/novamachina/exnihilosequentia/common/crafting/SingleItemSerializableRecipe.java
  src/main/java/novamachina/exnihilosequentia/common/crafting/compost/CompostRecipe.java
  src/main/java/novamachina/exnihilosequentia/common/crafting/crook/CrookRecipe.java
  src/main/java/novamachina/exnihilosequentia/common/crafting/crucible/CrucibleRecipe.java
  src/main/java/novamachina/exnihilosequentia/common/crafting/fluiditem/FluidItemRecipe.java
  src/main/java/novamachina/exnihilosequentia/common/crafting/fluidtransform/FluidTransformRecipe.java
  src/main/java/novamachina/exnihilosequentia/common/crafting/hammer/HammerRecipe.java
  src/main/java/novamachina/exnihilosequentia/common/crafting/sieve/SieveRecipe.java
Labels: improvement, 1.19
